version: '3.8'

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: 3cplus
      POSTGRES_PASSWORD: 3cplus
      POSTGRES_DB: 3cplus
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
